/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Gleibson Alves
 */
public class tela1 extends javax.swing.JFrame {

    /**
     * Creates new form tela1
     */
    public tela1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        painelPrincipal = new javax.swing.JPanel();
        painelSuper = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        painelLogin = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        painelelementoLogim = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        painelInferl = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        painelCentral = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        painelForme = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        painelCompForme = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(1215, 558));

        painelPrincipal.setLayout(new java.awt.BorderLayout());

        painelSuper.setBackground(new java.awt.Color(204, 204, 255));
        painelSuper.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/logo.png"))); // NOI18N
        painelSuper.add(jLabel1, java.awt.BorderLayout.CENTER);

        painelLogin.setBackground(new java.awt.Color(204, 204, 255));
        painelLogin.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("                                   ");
        painelLogin.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        jLabel3.setText("                               ");
        painelLogin.add(jLabel3, java.awt.BorderLayout.PAGE_END);

        jLabel4.setText("                 ");
        painelLogin.add(jLabel4, java.awt.BorderLayout.LINE_END);

        painelelementoLogim.setBackground(new java.awt.Color(204, 204, 255));
        painelelementoLogim.setLayout(new java.awt.GridLayout(2, 4, 15, 0));

        jLabel9.setText("Tipo:");
        painelelementoLogim.add(jLabel9);

        jLabel11.setText("Usuario");
        painelelementoLogim.add(jLabel11);

        jLabel10.setText("Senha");
        painelelementoLogim.add(jLabel10);
        painelelementoLogim.add(jLabel12);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar", "Admin", "Usuario" }));
        jComboBox1.setPreferredSize(new java.awt.Dimension(120, 20));
        painelelementoLogim.add(jComboBox1);
        painelelementoLogim.add(jTextField1);
        painelelementoLogim.add(jTextField2);

        jButton1.setText("Salvar");
        jButton1.setToolTipText("");
        painelelementoLogim.add(jButton1);

        painelLogin.add(painelelementoLogim, java.awt.BorderLayout.CENTER);

        painelSuper.add(painelLogin, java.awt.BorderLayout.LINE_END);

        painelPrincipal.add(painelSuper, java.awt.BorderLayout.PAGE_START);

        painelInferl.setBackground(new java.awt.Color(204, 204, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Gleibson Alves Engenheiro de Software");
        painelInferl.add(jLabel5);

        painelPrincipal.add(painelInferl, java.awt.BorderLayout.PAGE_END);

        painelCentral.setBackground(new java.awt.Color(0, 0, 51));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/lanche.jpg"))); // NOI18N
        painelCentral.add(jLabel6);

        painelForme.setPreferredSize(new java.awt.Dimension(590, 380));
        painelForme.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painelCompForme.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setText("Salvar");
        jButton3.setPreferredSize(new java.awt.Dimension(65, 25));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        painelCompForme.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 130, 40));

        jLabel13.setText(" Endereço");
        painelCompForme.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));
        painelCompForme.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 380, -1));

        jLabel15.setText(" RG");
        painelCompForme.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, -1));
        painelCompForme.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 180, -1));

        jLabel16.setText(" Sobrenome");
        painelCompForme.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 60, -1));

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        painelCompForme.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 230, -1));

        jLabel17.setText("Nome");
        painelCompForme.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        painelCompForme.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 140, -1));

        jLabel18.setText(" CPF");
        painelCompForme.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));
        painelCompForme.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 170, -1));

        jLabel19.setText(" Anotações");
        painelCompForme.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        painelCompForme.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 370, 100));

        jScrollPane1.setViewportView(painelCompForme);

        painelForme.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 570, 210));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("Controle de Usuários");
        painelForme.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jRadioButton1.setText("Administrador");
        painelForme.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jRadioButton2.setText("Usuário");
        painelForme.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        jRadioButton3.setText("Visitante");
        painelForme.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));
        painelForme.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 130, -1));

        jLabel8.setText("Buscar");
        painelForme.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, -1, -1));
        jLabel8.getAccessibleContext().setAccessibleName(" Buscar");

        jPanel1.setLayout(new java.awt.GridLayout(1, 0, 15, 0));

        jButton10.setText("Editar");
        jPanel1.add(jButton10);

        jButton8.setText("Excluir");
        jPanel1.add(jButton8);

        jButton9.setText("Listar");
        jPanel1.add(jButton9);

        jButton11.setText("Salvar");
        jPanel1.add(jButton11);

        painelForme.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 490, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Cadastro de Usuários");
        painelForme.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        painelCentral.add(painelForme);

        painelPrincipal.add(painelCentral, java.awt.BorderLayout.CENTER);

        jScrollPane3.setViewportView(painelPrincipal);

        getContentPane().add(jScrollPane3, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JPanel painelCentral;
    private javax.swing.JPanel painelCompForme;
    private javax.swing.JPanel painelForme;
    private javax.swing.JPanel painelInferl;
    private javax.swing.JPanel painelLogin;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JPanel painelSuper;
    private javax.swing.JPanel painelelementoLogim;
    // End of variables declaration//GEN-END:variables
}
